spring:
  application:
    name: TeachAgent
  datasource:
    url: jdbc:mysql://175.24.205.213:3306/teach_agent?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: username
    password: lmjnb666
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://hk.xty.app
      chat: qwen-max
      image:
        api-key: ${OPENAI_API_KEY}
        base-url: https://hk.xty.app
      audio:
        speech:
          api-key: ${OPENAI_API_KEY}
          base-url: https://hk.xty.app
  servlet:
    multipart:
      max-file-size: 50MB
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
server:
  port: 8088
  servlet:
    session:
      timeout: 36000s  # Session 超时时间，单位秒（这里设为 1 小时）
      cookie:
        max-age: PT36000S  # Cookie 有效期，单位秒
